# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nCm_ratio <- function(n1, m1, n2, m2) {
    .Call('forestTools_nCm_ratio', PACKAGE = 'forestTools', n1, m1, n2, m2)
}

timesTwo <- function(x) {
    .Call('forestTools_timesTwo', PACKAGE = 'forestTools', x)
}

